[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
authors = ["robin-thoene"]
license = "MIT"

[workspace.dependencies]
slint = "1.14.1"
sqlx = { version = "0.8.6", features = ["sqlite"] }
chrono = "0.4.42"
